uswitch/terrafying

README.md, lib/terrafying.rb
Changes required to get terraform 0.7.0 working.
=> Terraform 0.7.0

lib/terrafying.rb, lib/terrafying/cli.rb
used to visualise the resouce dependency graph.
This allows one to see which things will be creates in parallel or in order.
=> expose the terraform graph command

lib/terrafying.rb, lib/terrafying/version.rb
Tested on OSX only.
Pretty certain this will work without issue on other OS's, though NixOS is an unknown here.
=> Handle plugins

lib/terrafying/components/service.rb, lib/terrafying/components/templates/service.yaml, lib/terrafying/components/vpc.rb, lib/terrafying/components/vpn.rb
Don't rely on build in groups from main account bu allow passing ssh group as a parameter.
Also move openvpn-authz container to quai as we cant connect to private registry.
=> Modify service template

lib/terrafying/components/service.rb, lib/terrafying/components/zone.rb
So find functions can work properly
=> Pass context to add_record

lib/terrafying/components/vpc.rb
Use ssh_group tag value and fix select statement
=> Use ssh_group tag

Dockerfile
With the one specified in terrafying version.rb
=> Sync terraform version

lib/terrafying/components/support/register-vpn, lib/terrafying/components/vpn.rb
As we don't want to hardcode our ID in the source code
=> Pass Azure tenant ID

lib/terrafying/components/vpn.rb
=> Remove app registration

lib/terrafying/components/dynamicset.rb, lib/terrafying/components/letsencrypt.rb, spec/terrafying/components/dynamicset_spec.rb
Once I ran it on some larger applications I noticed some issues.
=> Couple of fixes

lib/terrafying/components/dynamicset.rb, lib/terrafying/components/service.rb, spec/terrafying/components/service_spec.rb
If we have a load balancer, some health checks on it and an ASG then
we should switch it to use ELB healthchecking to kill instances not
EC2
=> Enable ASG ELB healthchecks when appropriate

Dockerfile
=> Provider name needs a v in it

lib/terrafying/components/ignition.rb, spec/terrafying/components/ignition_spec.rb
It sucks to only find out you've missed some configuration when your
instance doesn't start up
=> Add some validation to units and files

Dockerfile, lib/terrafying/components/dynamicset.rb, lib/terrafying/version.rb, spec/terrafying/components/dynamicset_spec.rb, spec/terrafying/components/service_spec.rb
This will allow us to use auto rolling updates and automate deployments
further
=> Create ASGs via CloudFormation template

lib/terrafying/components/dynamicset.rb
This will make the name reappear in the UI
=> Uppercase name tag on ASGs

lib/terrafying/aws.rb, lib/terrafying/version.rb
Want to be able to look up ASGs so that we can steal the current
settings for instance min, max, desired.
=> Add function to get ASGs by tags

Dockerfile
The entrypoint script runs under bash.
=> Add bash to terraform rundeps

lib/terrafying/aws.rb
These changes aim to improve the Route53 FindHostedZoneByTag method by caching the results of the AWS API calls for the duration of the run. This avoids having to repeat the calls when multiple finds are done in a session.
- Add jitter backoff to all AWS api calls
- Cache results of Route53 calls to avoid overwhelming the Route53 API and throttling.
=> Improve Route53 Find Hosted Zone by Tag

lib/terrafying/aws.rb, terrafying.gemspec
- Switch to extend minimum retry time
- Bump to 7 retries
=> Extend wait time for retrying AWS calls.

lib/terrafying/generator.rb, spec/terrafying/generator_spec.rb
We can have more than one of the same provider with difference
aliases.
https://www.terraform.io/docs/configuration/providers.html
=> Output a reference to the provider

lib/terrafying/generator.rb, spec/terrafying/generator_spec.rb
This supports multiple providers of the same type with aliases
=> Change providers to set

lib/terrafying/aws.rb, lib/terrafying/cli.rb, lib/terrafying/generator.rb, spec/terrafying/generator_spec.rb
An attempt to integrate the good things from the terrafying-2 branch without the braking changes. Also sadly not the code reduction yet though
=> Terrafying loves 2

lib/terrafying/aws.rb, terrafying.gemspec
Lets us fetch the broker list for doing more terrafying things
=> Add a get brokers function to terrafying
