Gemfile.lock, README.md, lib/terrafying/generator.rb, lib/terrafying/version.rb
This includes application load balancer (alb's).
Should be backwards compatible, and you only need to upgrade terraform if you're using the new ALB stuff.
=> Updates for terraform 7.1

README.md, lib/terrafying.rb, lib/terrafying/generator.rb, lib/terrafying/version.rb
This requires all DSL generation to be wrapped in a block passed to `Terrafying::Generator.generate`
This is a major breaking change, but upgrading is very simple.
This means this gem can be used more more safely with other ruby code.
Fixes #6.
=> Stop patching DSL onto main

lib/terrafying/generator.rb
Attempt to get rid of a hardcoded whitelist of resource types; unfortunately a few helper functions seem to trigger method_missing, so I had to exclude them - ending up with a different kind of whitelist... Any better way of doing this?
=> Dynamically call the resource function instead of hardcoded whitelist

lib/terrafying.rb, lib/terrafying/version.rb
Problem 
===
1. Terrafying doesn't check for terraform as a requirement, which means when you try and `plan` or `apply` it outputs nothing to tell the user they haven't installed terraform
2. As terraform is still in baby stages, it's being under active development which means new versions keep cropping up - this poses a problem when users have an older version than the one someone else used on the same spec. Terraform will error and not let you continue.
Solution
===
- Checks for terraform in your path before you can execute any configuration
- `Terrafying::CLI_VERSION` has now been set at `0.8.0` and any person trying to use an older version or newer version of terraform will get an error message instructing them to use the CLI defined version in the gem. 
Potential issues
===
As …
=> Check for terraform existence + version

Gemfile.lock, lib/terrafying/version.rb
This point release removes a new provider that was targeting windows users.
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md
=> Upgrade Terraform version to 0.8.4

README.md, lib/terrafying/version.rb
0.8.5 (26 January 2017)
BACKWARDS INCOMPATIBILITIES / NOTES:
provider/aws: We no longer prefix an ECR repository address with https://
provider/google: google_project has undergone significant changes. Existing configs and state should continue to work as they always have, but new configs and state will exhibit some new behaviour, including actually creating and deleting projects, instead of just referencing them. See https://www.terraform.io/docs/providers/google/r/google_project.html for more details.
see https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md for more info.
=> Upgrades the terraform version

lib/terrafying.rb
This moves from things like:
```
~ aws_iam_role_policy.broadband_sales_dynamodb_policy
policy: "{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Allow\",\n            \"Action\": [\n                \"dynamodb:*\"\n            ],\n            \"Resource\": [\n                \"arn:aws:dynamodb:eu-west-1:136393635417:table/broadband_sales_approval_rates\",\n                \"arn:aws:dynamodb:eu-west-1:136393635417:table/broadband_sales_approval_rates/index/date-index\",\n                \"arn:aws:dynamodb:eu-west-1:136393635417:table/broadband-tracking-dev\",\n                \"arn:aws:dynamodb:eu-west-1:136393635417:table/broadband-tracking-production\"\n            ]\n        }\n    ]\n}" => "{\n  \"Version\": \"2012-10-17\",\n …
```
=> Make json diffs readable, to avoid 'Looks right' on policies

lib/terrafying/components/service.rb
Device name must be in form of: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
We now require user to provide device name
=> Don't generate device name

lib/terrafying/aws.rb, lib/terrafying/components/vpc.rb, lib/terrafying/components/zone.rb
This PR implements `find_by_tag` method for `Zone` component. It will allow us to use `vpc.find`output to `vpn.create` method.
Also this fixed an order of vpc resource creation so now `@id` is created ahead of tag that needs it's value.
=> Find zone by tag

lib/terrafying/aws.rb
Each doesn't return anything. Any returns true or false based on
condition.
=> Replace each with any

lib/terrafying/components/vpc.rb
The group attribute was not exported but it is used here: https://github.com/uswitch/terrafying/blob/master/lib/terrafying/components/service.rb#L214 making it null and thus failing in terraform:
```
Error: Failed to load root config module: Error parsing /Users/piotrkomborski/dev/src/github.com/uswitch/terrafying-audit/tmp/2e2cd1a5-4ce6-48e5-
ac37-9ef1bbaa87d5/vpn.tf.json: unexpected token while parsing list: NULL
```
=> Export ssh group

lib/terrafying/components/vpn.rb, lib/terrafying/components/zone.rb
We need this to get token from Azure. Also, `acme/autocert` doesn’t like dot at the end of fqdn
=> Pass secrets

lib/terrafying/components/service.rb, lib/terrafying/components/templates/service.yaml, spec/terrafying/components/service_spec.rb
This will address issue #39 as volume names will now be based on mount point.
=> Volume mount name

lib/terrafying/components/templates/service.yaml, spec/terrafying/components/service_spec.rb
Systemd units will not be loaded without a WantedBy target. This will ensure ensure that volumes are mounted before the docker services as well.
=> Add WantedBy target to mount units for coreos to load on boot

lib/terrafying/components/ca.rb, lib/terrafying/components/letsencrypt.rb, lib/terrafying/components/selfsignedca.rb, spec/support/shared_examples/ca.rb
If we are creating a CA cert in the same run as creating
a service, it should also wait for the CA cert to exist before
letting the machine spin up
=> Make sure we depend on the ca cert when needed

lib/terrafying/components/ca.rb, lib/terrafying/components/dynamicset.rb, lib/terrafying/components/endpoint.rb, lib/terrafying/components/instance.rb, lib/terrafying/components/letsencrypt.rb, lib/terrafying/components/loadbalancer.rb, lib/terrafying/components/selfsignedca.rb, lib/terrafying/components/service.rb, lib/terrafying/components/staticset.rb, lib/terrafying/components/subnet.rb, lib/terrafying/components/vpc.rb, lib/terrafying/components/zone.rb, lib/terrafying/generator.rb
Terraform resource names have a limitted set of characters that can
appear. This drops some common characters that are not allowed
=> Add tf_safe function to remove bad chars

lib/terrafying/components/dynamicset.rb
We usually want to be able to see what's going on with our ASGs,
so enable everything!
=> Enabled ASG metrics

lib/terrafying/components/vpn.rb, spec/terrafying/components/vpn_spec.rb
Having the VPN default to no authentication was not such a great idea.
This forces the use of a provider
=> Require a provider by default

lib/terrafying/dynamodb.rb, lib/terrafying/generator.rb
People might run this who aren't trying to provision infrastructure
in eu-west-1
The allows the overriding of the default region by specifying an `AWS_REGION` environment variable.
See #59
=> Allow region to be varied

lib/terrafying/generator.rb, lib/terrafying/version.rb, spec/terrafying/generator_spec.rb
Datadog lowercases the asg name when it imports metrics, so when
we are configuring the dashboards we need to make sure we lowercase
the asg name too. This lets us do that
=> output_of returns a ref that allows manipulation

lib/terrafying.rb, lib/terrafying/cli.rb
In general the `plan` method is preferable but in cases where we don't
want to call that on un-checked code (e.g. where passwords might be
leaked) `validate` provides a basic check that the generated terraform
is free from basic errors.
=> Add validate method

lib/terrafying.rb, lib/terrafying/cli.rb
Adds the ability to use `--lock-timeout=XXs` which will be passed to terraform. 
Since we now rely on terraform for state locking this causes lots of erros with state lock contention on the builds. This flag will allow us to configure a build to wait a specified time before failing.
=> Add an option to set terraform's state lock timeout

lib/terrafying/util.rb
This removes whitespace from the final user data saving a couple of hunderd to thousand bytes
=> Don't pretty generate json for instances

lib/terrafying/aws.rb
We'll need to look at implementing a find for private zones in the future as VPC info doesn't get returned from the list call and could become quite expensive to lookup.
=> Don't return private zones when finding a zone by fqdn as we get duplicates

lib/terrafying/generator.rb, spec/terrafying/generator_spec.rb
In order to pin versions of the AWS provider we need to be able to
define the provider rather than it being defaulted. This maintains
backwards compatibility by defaulting the providers if not already
stated
=> Allow overriding of the default providers

lib/terrafying/generator.rb
It doesn't like it and it has cropped up with wildcard domain names
=> Drop * when creating a terraform safe string

terrafying.gemspec
Updated `netaddr` version to `>=2.0.4` as per github security alert
=> Update netaddr version

terrafying.gemspec
Reverts uswitch/terrafying#114
`2.0.4` is not compatible as mentioned [here](https://github.com/dspinhirne/netaddr-rb)
=> Revert "Update netaddr version"

lib/terrafying/generator.rb, spec/terrafying/generator_spec.rb
This is the test case;
```
Terrafying::Generator.generate do
role = tf_module 'role', 
source: './role',
providers: {
aws: "aws"
},
created_by: 'wai'
policy = tf_module('policy', source: './policy', policy_name: 'test_policy')
resource :aws_iam_role_policy_attachment, "attach_role",
role: role['name'],
policy_arn: policy['policy_arn']
end
```
`policy_arn` and `name` were outputs of the module
=> Add support for modules to Terrafying

lib/terrafying/generator.rb
Adds the ability to add required_providers and required_versions inside `terraform` block.
This is necessary to enable upgrading to TF 0.13
Works as;
```ruby
Terrafying::Generator.generate do
required_provider('aws', {"source" => "hashicorp/aws", "version" =>  "~> 3.42.0"})
required_provider('acme', {"source" => "vancluever/acme", "version" =>  "~> 2.4.0"})
required_version(">= 0.13")
end
```
As well as;
```ruby
Terrafying::Generator.required_provider('aws', {"source" => "hashicorp/aws", "version" =>  "~> 3.42.0"})
Terrafying::Generator.required_provider('acme', {"source" => "vancluever/acme", "version" =>  "~> 2.4.0"})
Terrafying::Generator.required_version(">= 0.13")
```
Here for reference: https://www.notion.so/rvu/Migrating-a-Terrafying-repo-from-Terraform-v0-12-to-Terraform-v0-13-df7a …
=> Add ability to add required_providers and required_version
